# Setup
title:        Mohamed Ibrahim
tagline:      Android developer | Self-taught Programmer | English Learner
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mohamed Ibrahim
  url:        https://twitter.com/MohamedISoliman

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

#theme: jekyll-theme-cayman

