# Setup
title:        GeekyMind
tagline:      Break things - Have fun - Never give up
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mohamed Ibrahim
  url:        mibrahim.dev@gmail.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown